# apiVersion: v1
# kind: ResourceQuota
apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: crq-sample
spec:
  selector:
    annotations: 
      openshift.io/requester: ac-admin
    labels: null 
  quota:
    hard:
      services.nodeports: '0'
      secrets: '250'
      services.loadbalancers: '0'
      persistentvolumeclaims: '100'
      ephemeral-storage: 20Gi
      requests.memory: 48Gi
      pods: '200'
      requests.storage: 600Gi
      limits.cpu: '72'
      limits.memory: 288Gi
      configmaps: '400'
      services: '200'
      requests.cpu: '12'
